name = "SpaceDataModel"
uuid = "0b37b92c-f0c5-4a52-bd5c-390dec20857c"
version = "0.2.2"
authors = ["Zijin Zhang <zzj956959688@gmail.com>"]

[workspace]
projects = ["docs"]

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"

[weakdeps]
CommonDataModel = "1fbeeb36-5f17-413c-809b-666fb144f157"
DimensionalData = "0703355e-b756-11e9-17c0-8b28908087d0"

[extensions]
SpaceDataModelCommonDataModelExt = "CommonDataModel"
SpaceDataModelDimensionalDataExt = "DimensionalData"

[compat]
Accessors = "0.1"
CommonDataModel = "0.4"
Dates = "1"
DimensionalData = "0.29"
julia = "1.10"
