name = "SpaceDataModel"
uuid = "0b37b92c-f0c5-4a52-bd5c-390dec20857c"
authors = ["Zijin Zhang <zzj956959688@gmail.com>"]
version = "0.1.6"

[deps]
Accessors = "7d9f7c33-5ae7-4f3b-8dc6-eff91059b697"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"

[compat]
Accessors = "0.1"
Dates = "1"
julia = "1.10"
